//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecompildPOS.Resources.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecompildPOS.Resources.Language.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        internal static string ACCOUNT_PAGE_TITLE {
            get {
                return ResourceManager.GetString("ACCOUNT_PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Transactions posted successfully.
        /// </summary>
        internal static string ACCOUNT_TRANSACTION_MODULE_ACCOUNT_TRANSACTIONS_POSTED {
            get {
                return ResourceManager.GetString("ACCOUNT_TRANSACTION_MODULE_ACCOUNT_TRANSACTIONS_POSTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts posted successfully.
        /// </summary>
        internal static string ACCOUNTS_MODULE_ACCOUNTS_POSTED {
            get {
                return ResourceManager.GetString("ACCOUNTS_MODULE_ACCOUNTS_POSTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Code.
        /// </summary>
        internal static string ADD_ACCOUNT_PAGE_ACCOUNT_CODE {
            get {
                return ResourceManager.GetString("ADD_ACCOUNT_PAGE_ACCOUNT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string ADD_ACCOUNT_PAGE_ADDRESS {
            get {
                return ResourceManager.GetString("ADD_ACCOUNT_PAGE_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string ADD_ACCOUNT_PAGE_BALANCE {
            get {
                return ResourceManager.GetString("ADD_ACCOUNT_PAGE_BALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Limit.
        /// </summary>
        internal static string ADD_ACCOUNT_PAGE_CREDIT_LIMIT {
            get {
                return ResourceManager.GetString("ADD_ACCOUNT_PAGE_CREDIT_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string ADD_ACCOUNT_PAGE_EMAIL {
            get {
                return ResourceManager.GetString("ADD_ACCOUNT_PAGE_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ADD_ACCOUNT_PAGE_NAME {
            get {
                return ResourceManager.GetString("ADD_ACCOUNT_PAGE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string ADD_ACCOUNT_PAGE_PHONE_NUMBER {
            get {
                return ResourceManager.GetString("ADD_ACCOUNT_PAGE_PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Account.
        /// </summary>
        internal static string ADD_ACCOUNT_PAGE_SAVE_ACCOUNT {
            get {
                return ResourceManager.GetString("ADD_ACCOUNT_PAGE_SAVE_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Account.
        /// </summary>
        internal static string ADD_ACCOUNT_PAGE_TITLE {
            get {
                return ResourceManager.GetString("ADD_ACCOUNT_PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string ALERT {
            get {
                return ResourceManager.GetString("ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string ALERT_HEADING_ALERT {
            get {
                return ResourceManager.GetString("ALERT_HEADING_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string ALERT_HEADING_WARNING {
            get {
                return ResourceManager.GetString("ALERT_HEADING_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet Connection.
        /// </summary>
        internal static string ALERT_NO_INTERNET {
            get {
                return ResourceManager.GetString("ALERT_NO_INTERNET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please contact admin.
        /// </summary>
        internal static string ALERT_SOMETHING_WENT_WRONG {
            get {
                return ResourceManager.GetString("ALERT_SOMETHING_WENT_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Completed.
        /// </summary>
        internal static string ALERT_SYNC_COMPLETED {
            get {
                return ResourceManager.GetString("ALERT_SYNC_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync In Progress.
        /// </summary>
        internal static string ALERT_SYNC_IN_PROGRESS {
            get {
                return ResourceManager.GetString("ALERT_SYNC_IN_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Started.
        /// </summary>
        internal static string ALERT_SYNC_STARTED {
            get {
                return ResourceManager.GetString("ALERT_SYNC_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business expenses posted successfully.
        /// </summary>
        internal static string BUSINESS_EXPENSES_MODULE_BUSINESS_EXPENSES_POSTED {
            get {
                return ResourceManager.GetString("BUSINESS_EXPENSES_MODULE_BUSINESS_EXPENSES_POSTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Expense.
        /// </summary>
        internal static string BUSINESS_FINANCE_PAGE_ADD_EXPENSE {
            get {
                return ResourceManager.GetString("BUSINESS_FINANCE_PAGE_ADD_EXPENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Name.
        /// </summary>
        internal static string BUSINESS_FINANCE_PAGE_BUSINESS_NAME {
            get {
                return ResourceManager.GetString("BUSINESS_FINANCE_PAGE_BUSINESS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Amount.
        /// </summary>
        internal static string BUSINESS_FINANCE_PAGE_EXPENSE_AMOUNT {
            get {
                return ResourceManager.GetString("BUSINESS_FINANCE_PAGE_EXPENSE_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense Name.
        /// </summary>
        internal static string BUSINESS_FINANCE_PAGE_EXPENSE_NAME {
            get {
                return ResourceManager.GetString("BUSINESS_FINANCE_PAGE_EXPENSE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Expense Info.
        /// </summary>
        internal static string BUSINESS_FINANCE_PAGE_EXPENSE_SAVE {
            get {
                return ResourceManager.GetString("BUSINESS_FINANCE_PAGE_EXPENSE_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Earning.
        /// </summary>
        internal static string BUSINESS_FINANCE_PAGE_MONTHLY_EARNING {
            get {
                return ResourceManager.GetString("BUSINESS_FINANCE_PAGE_MONTHLY_EARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Finance.
        /// </summary>
        internal static string BUSINESS_FINANCE_PAGE_TITLE {
            get {
                return ResourceManager.GetString("BUSINESS_FINANCE_PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business finances posted successfully.
        /// </summary>
        internal static string BUSINESS_FINANCES_MODULE_BUSINESS_FINANCES_POSTED {
            get {
                return ResourceManager.GetString("BUSINESS_FINANCES_MODULE_BUSINESS_FINANCES_POSTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business registered successfully.
        /// </summary>
        internal static string BUSINESS_MODULE_BUSINESS_REGISTERED_TEXT {
            get {
                return ResourceManager.GetString("BUSINESS_MODULE_BUSINESS_REGISTERED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some issue with business registration contact admin.
        /// </summary>
        internal static string BUSINESS_MODULE_BUSINESS_REGISTRATION_ISSUE_TEXT {
            get {
                return ResourceManager.GetString("BUSINESS_MODULE_BUSINESS_REGISTRATION_ISSUE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business update submitted successfully.
        /// </summary>
        internal static string BUSINESS_MODULE_BUSINESSES_UPDATED {
            get {
                return ResourceManager.GetString("BUSINESS_MODULE_BUSINESSES_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Category.
        /// </summary>
        internal static string BUSINESS_PAGE_BUSINESS_CATEGORY {
            get {
                return ResourceManager.GetString("BUSINESS_PAGE_BUSINESS_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Number.
        /// </summary>
        internal static string BUSINESS_PAGE_BUSINESS_LICENSE_NUMBER {
            get {
                return ResourceManager.GetString("BUSINESS_PAGE_BUSINESS_LICENSE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Name.
        /// </summary>
        internal static string BUSINESS_PAGE_BUSINESS_NAME {
            get {
                return ResourceManager.GetString("BUSINESS_PAGE_BUSINESS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Owner.
        /// </summary>
        internal static string BUSINESS_PAGE_BUSINESS_OWNER {
            get {
                return ResourceManager.GetString("BUSINESS_PAGE_BUSINESS_OWNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Type.
        /// </summary>
        internal static string BUSINESS_PAGE_BUSINESS_TYPE {
            get {
                return ResourceManager.GetString("BUSINESS_PAGE_BUSINESS_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Profile.
        /// </summary>
        internal static string BUSINESS_PAGE_TITLE {
            get {
                return ResourceManager.GetString("BUSINESS_PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check device permissions in system.
        /// </summary>
        internal static string CONNECTION_HELPER_CHECK_PERMISSIONS {
            get {
                return ResourceManager.GetString("CONNECTION_HELPER_CHECK_PERMISSIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to server.
        /// </summary>
        internal static string CONNECTION_HELPER_UNABLE_TO_CONNECT_SERVER {
            get {
                return ResourceManager.GetString("CONNECTION_HELPER_UNABLE_TO_CONNECT_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of day report posted successfully.
        /// </summary>
        internal static string END_OF_DAY_REPORT_MODULE_END_OF_DAY_REPORT_POSTED {
            get {
                return ResourceManager.GetString("END_OF_DAY_REPORT_MODULE_END_OF_DAY_REPORT_POSTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Barcode.
        /// </summary>
        internal static string GENERATE_BAR_CODE {
            get {
                return ResourceManager.GetString("GENERATE_BAR_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate QR Code.
        /// </summary>
        internal static string GENERATE_QR_CODE {
            get {
                return ResourceManager.GetString("GENERATE_QR_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HOME_PAGE_HOME {
            get {
                return ResourceManager.GetString("HOME_PAGE_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string LOGIN_PAGE_LOGIN {
            get {
                return ResourceManager.GetString("LOGIN_PAGE_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LOGIN_PAGE_PASSWORD {
            get {
                return ResourceManager.GetString("LOGIN_PAGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        internal static string LOGIN_PAGE_REGISTER {
            get {
                return ResourceManager.GetString("LOGIN_PAGE_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string LOGIN_PAGE_SAVE_USERNAME_PASSWORD {
            get {
                return ResourceManager.GetString("LOGIN_PAGE_SAVE_USERNAME_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string LOGIN_PAGE_USER_NAME {
            get {
                return ResourceManager.GetString("LOGIN_PAGE_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Sale.
        /// </summary>
        internal static string MAKE_SALE_PAGE_TITLE {
            get {
                return ResourceManager.GetString("MAKE_SALE_PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string MENU_PAGE {
            get {
                return ResourceManager.GetString("MENU_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string MENU_PAGE_ABOUT {
            get {
                return ResourceManager.GetString("MENU_PAGE_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        internal static string MENU_PAGE_ACCOUNTS {
            get {
                return ResourceManager.GetString("MENU_PAGE_ACCOUNTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Finances.
        /// </summary>
        internal static string MENU_PAGE_BUSINESS_FINANCES {
            get {
                return ResourceManager.GetString("MENU_PAGE_BUSINESS_FINANCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Profile.
        /// </summary>
        internal static string MENU_PAGE_BUSINESS_PROFILE {
            get {
                return ResourceManager.GetString("MENU_PAGE_BUSINESS_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of Day Report.
        /// </summary>
        internal static string MENU_PAGE_END_OF_DAY {
            get {
                return ResourceManager.GetString("MENU_PAGE_END_OF_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Transactions.
        /// </summary>
        internal static string MENU_PAGE_FINANCIAL {
            get {
                return ResourceManager.GetString("MENU_PAGE_FINANCIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        internal static string MENU_PAGE_INVENTORY {
            get {
                return ResourceManager.GetString("MENU_PAGE_INVENTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string MENU_PAGE_PRODUCTS {
            get {
                return ResourceManager.GetString("MENU_PAGE_PRODUCTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order.
        /// </summary>
        internal static string MENU_PAGE_PURCHASE_ORDER {
            get {
                return ResourceManager.GetString("MENU_PAGE_PURCHASE_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        internal static string MENU_PAGE_QUICK_SALE_PAGE {
            get {
                return ResourceManager.GetString("MENU_PAGE_QUICK_SALE_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Order.
        /// </summary>
        internal static string MENU_PAGE_SALES_ORDER {
            get {
                return ResourceManager.GetString("MENU_PAGE_SALES_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MENU_PAGE_SETTINGS {
            get {
                return ResourceManager.GetString("MENU_PAGE_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string MENU_PAGE_USERS {
            get {
                return ResourceManager.GetString("MENU_PAGE_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product.
        /// </summary>
        internal static string PRODUCT_PAGE_ADD_NEW_PRODUCT {
            get {
                return ResourceManager.GetString("PRODUCT_PAGE_ADD_NEW_PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Product Details.
        /// </summary>
        internal static string PRODUCT_PAGE_ENTER_PRODUCT_DETAILS {
            get {
                return ResourceManager.GetString("PRODUCT_PAGE_ENTER_PRODUCT_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        internal static string PRODUCT_PAGE_PRODUCT_BAR_CODE {
            get {
                return ResourceManager.GetString("PRODUCT_PAGE_PRODUCT_BAR_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode 2.
        /// </summary>
        internal static string PRODUCT_PAGE_PRODUCT_BAR_CODE2 {
            get {
                return ResourceManager.GetString("PRODUCT_PAGE_PRODUCT_BAR_CODE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Details.
        /// </summary>
        internal static string PRODUCT_PAGE_PRODUCT_DETAILS {
            get {
                return ResourceManager.GetString("PRODUCT_PAGE_PRODUCT_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PRODUCT_PAGE_PRODUCT_NAME {
            get {
                return ResourceManager.GetString("PRODUCT_PAGE_PRODUCT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Code.
        /// </summary>
        internal static string PRODUCT_PAGE_PRODUCT_QR_CODE {
            get {
                return ResourceManager.GetString("PRODUCT_PAGE_PRODUCT_QR_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU Code.
        /// </summary>
        internal static string PRODUCT_PAGE_PRODUCT_SKU_CODE {
            get {
                return ResourceManager.GetString("PRODUCT_PAGE_PRODUCT_SKU_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Product .
        /// </summary>
        internal static string PRODUCT_PAGE_UPDATE_PRODUCTS {
            get {
                return ResourceManager.GetString("PRODUCT_PAGE_UPDATE_PRODUCTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products posted successfully.
        /// </summary>
        internal static string PRODUCTS_MODULE_PRODUCTS_POSTED {
            get {
                return ResourceManager.GetString("PRODUCTS_MODULE_PRODUCTS_POSTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already user?.
        /// </summary>
        internal static string REGISTER_PAGE_ALREADY_USER {
            get {
                return ResourceManager.GetString("REGISTER_PAGE_ALREADY_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Name.
        /// </summary>
        internal static string REGISTER_PAGE_BUSINESS_NAME {
            get {
                return ResourceManager.GetString("REGISTER_PAGE_BUSINESS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string REGISTER_PAGE_EMAIL_ADDRESS {
            get {
                return ResourceManager.GetString("REGISTER_PAGE_EMAIL_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        internal static string REGISTER_PAGE_MOBILE_NUMBER {
            get {
                return ResourceManager.GetString("REGISTER_PAGE_MOBILE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string REGISTER_PAGE_REGISTER {
            get {
                return ResourceManager.GetString("REGISTER_PAGE_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        internal static string SYNC_PAGE_SYNC {
            get {
                return ResourceManager.GetString("SYNC_PAGE_SYNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesn&apos;t exist.
        /// </summary>
        internal static string USERDOESNOTEXIST {
            get {
                return ResourceManager.GetString("USERDOESNOTEXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users posted successfully.
        /// </summary>
        internal static string USERS_MODULE_USER_POSTED {
            get {
                return ResourceManager.GetString("USERS_MODULE_USER_POSTED", resourceCulture);
            }
        }
    }
}
